permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: lostmarble 
  email: lostmarble@qq.com
  link: http://lostmarble.github.io
  weibo: http://weibo.com/lostmarble
  github: http://github.com/lostmarble

# 站点信息
title: 消息的玻璃球 
description: 技术博客
url: http://lostmarble.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: pics/photo.gif
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org
#
## disqus 设置
#disqus:
#  shortname: lostmarble 
